[workspace]
members = [
    "cli",
    "game"
]

[workspace.package]
name = "puzzle-15"
version = "0.0.1"
edition = "2021"
authors = [ "Olexandr Koval <kovalidis@gmail.com>" ]

[workspace.dependencies]
anyhow = "1.0.71"
