[package]
name = "puzzle_15"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
clap = { version = "4.3.8", features = ["derive"] }
game = { path = "../game" }
rand = "0.8.5"

[dev-dependencies]
similar-asserts = "1.4.2"
