[package]
name = "puzzle_15"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
game = { path = "../game" }

[dev-dependencies]
similar-asserts = "1.4.2"
